version: "3.7"
services:
  front:
    image: node:16.14.0
    working_dir: /usr/src/app
    tty: true
    ports: 
    - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "npm install &&
      npm install nodemon -g &&
      nodemon src/server.js"
  back:
    volumes:
      - ./app:/app
    build: .
    ports:
      - 8080:8080